### PR TITLE
Reduce dependency footprint

### PR DESCRIPTION
**Pull request by Erotemic**
The primary purpose of this PR is to reduce the default dependency footprint of distinctipy.

I added distinctipy as a dependency to my [kwimage](https://gitlab.kitware.com/computer-vision/kwimage) and that has increased the dependency surface by a significant amount. The code in distinctipy is fairly lightweight and only uses a small number of the listed dependencies. The core functionality only depends on numpy.

Because I this is a significant change (in the sense that it could break other people who use this library), I also put a significant amount of working into bolstering the tests and ensuring that the library functions with the new paired down dependencies.

A list of changes I made:

* Split requirements.txt into sub files. Namely: requirements/runtime.txt, requirements/tests.txt, requirements/docs.txt, and requirements/optional.txt The requirements.txt now points to them. So `pip install -r requirements.txt` still works as before.
* Updated setup.py to include optional dependencies in the `extras_require` section.
* Removed a potential circular dependency
* Updated the CI script. Now, tests are run on multiple operating systems, and there are two variants of the tests: "full" and "minimal", which runs tests with full/minimal dependencies to verify functionality.
* Added more tests and significantly expanded the coverage: (previous tests got 35% coverage, new tests have 85% coverage).
* I moved the big 400 item dictionary from colorsets to a new module _colorsets_data. It made my editor bug out while there was another load on the CPU. This is mainly just separating data from logic. Can revert if you'd like.
* Added hook to upload coverage to codecov.io and added a badge to the README (you may have to give codecov.io permissions, or we can remove the badge / upload and just report coverage to the terminal).

The upshot of all of this is now, unless you already have matplotlib/pandas installed you have to run `pip install distinctipy[all]` in order to run the examples. If you just run `pip install distinctipy` it will now only install numpy (and the tests verify that all of the core code works in this case).

### CODE REVIEW

**Comment by Erotemic** [comment]
Not sure why the GH Actions aren't running on this PR page. They are running and passing on my fork CI: https://github.com/Erotemic/distinctipy/actions/runs/1613163278


```
============================= test session starts ==============================
platform linux -- Python 3.10.1, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/runner/work/distinctipy/distinctipy
plugins: cov-3.0.0
collected 16 items

../tests/test_distinctipy.py ...........                                 [ 68%]
../tests/test_examples.py .....                                          [100%]

---------- coverage: platform linux, python 3.10.1-final-0 -----------
Name                                                                                                 Stmts   Miss  Cover
------------------------------------------------------------------------------------------------------------------------
/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/distinctipy/__init__.py             14      0   100%
/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/distinctipy/_colorsets_data.py       1      0   100%
/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/distinctipy/colorblind.py          146     26    82%
/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/distinctipy/colorsets.py            22      8    64%
/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/distinctipy/distinctipy.py         158     18    89%
/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/distinctipy/examples.py             38      4    89%
------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                                  379     56    85%
```

**Comment by jack89roberts** [comment]
Thanks again @Erotemic ! As you say this is a bigger change so I'll need to find some time to look through it properly. As I understand it the changes are backwards compatible _except_ for matplotlib and pandas (+ dev/docs stuff) not being bundled as a default dependency after this?

**Comment by Erotemic** [comment]
Correct. As long as matplotlib+pandas are installed, there are no incompatible changes. 

I could have gotten away with making this PR much smaller, but I felt it was important to ensure the code I was changing was also well-tested. You'll notice the bulk of the PR is new tests and modifications to the github actions yaml. Everything else is shuffling of import, adding a few kwargs to toggle plt.show, minor tweaks, etc...

#### Demo What Works Out of The Box

In a fresh environment running the following works just fine:

```bash
pip install distinctipy

python -c "import distinctipy; print(distinctipy.get_colors(3, rng=0))"
```

And produces:

```
[(0.8117763047492077, 0.00901067759468821, 0.9907915790130629), (0.0, 1.0, 0.0), (1.0, 0.5, 0.0)]
```

#### Demo What No Longer Works Out of The Box

However, if you were to do:

```bash
python -c "import distinctipy; print(distinctipy.color_swatch(distinctipy.get_colors(10)))"
```

You will get an error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/repo/distinctipy/distinctipy.py", line 359, in color_swatch
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
```

Which is fairly straightforward to debug. But if you either install matplotlib (`via pip install matplotlib`) or denote that distinctipy should be installed with optional dependencies  `pip install distinctipy[optional]` then it will work. 

Almost no-one who is using distinctipy will notice this error because usually matplotlib / pandas are dependencies of something else in the stack. So they will usually be available, even if distinctipy didn't specifically request them. However, for those working with minimal dependency stacks they will notice a significant reduction in dependencies.

**Comment by Erotemic** [comment]
Also, it might be a good idea to enable running Actions for .github/workflows/pythonapp.yml in this PR to ensure everything passes. I'm not quite sure how to do that. I'm hoping you have some menu on your end for it.

Almost all tests pass on my fork's actions page: https://github.com/Erotemic/distinctipy/actions/runs/1619778549 except for one with pypy3.7 on ubuntu. It has something to do with a pandas c-extension. Not sure how much you care about testing pypy, we could disable that or mark it as allowed to fail.

**Comment by Erotemic** [comment]
Looks like your fix for the CI worked! Pending your review, I think this is ready for merger.

The last change I made was fixing up the codecov badge now that you've got it running. Because there isn't a branch on this remote where coverage was computed, the badge currently reads "unknown" but that will change after this PR is merged. The link does work if you click on it, and it does show the coverage for this PR on the main page.
[codecov](https://codecov.io/gh/alan-turing-institute/distinctipy)

Lastly, once pandas releases pandas-dev/pandas#44253 you can un-comment [line 48](https://github.com/alan-turing-institute/distinctipy/blob/4cd7d519b54cd33482de6627febde9b208eb093f/.github/workflows/pythonapp.yml#L48) in pythonapp.yml, which will re-enable testing on pypy. (I wasn't sure how to enable it but allow it to fail; the failure certainly isn't distinctipy's fault). But I think the current state is merge-worthy in the meantime.

**Review by jack89roberts — APPROVED** [review]

**Comment by jack89roberts** [comment]
Great I'm happy with these @Erotemic , thanks again! I made a few minor changes/additions to the readme and added a few more linting/code quality checks. Merging them now.

**Comment by Erotemic** [comment]
Thank you! The dependency difference is stark!

```bash
pip install johnnydep
```

### Old:

```bash
johnnydep distinctipy==1.2.0
``` 

```
name                                                                   summary
---------------------------------------------------------------------  ------------------------------------------------------------------------------------------------------------
distinctipy==1.2.0                                                     A lightweight package for generating visually distinct colours.
├── cycler                                                             Composable style cycles
├── kiwisolver                                                         A fast implementation of the Cassowary constraint solver
├── matplotlib                                                         Python plotting package
│   ├── cycler>=0.10                                                   Composable style cycles
│   ├── fonttools>=4.22.0                                              Tools to manipulate font files
│   ├── kiwisolver>=1.0.1                                              A fast implementation of the Cassowary constraint solver
│   ├── numpy>=1.17                                                    NumPy is the fundamental package for array computing with Python.
│   ├── packaging>=20.0                                                Core utilities for Python packages
│   │   └── pyparsing!=3.0.5,>=2.0.2                                   Python parsing module
│   ├── pillow>=6.2.0                                                  Python Imaging Library (Fork)
│   ├── pyparsing>=2.2.1                                               Python parsing module
│   └── python-dateutil>=2.7                                           Extensions to the standard Python datetime module
│       └── six>=1.5                                                   Python 2 and 3 compatibility utilities
├── nbsphinx                                                           Jupyter Notebook Tools for Sphinx
│   ├── docutils                                                       Docutils -- Python Documentation Utilities
│   ├── jinja2                                                         A very fast and expressive template engine.
│   │   └── MarkupSafe>=2.0                                            Safely add untrusted strings to HTML/XML markup.
│   ├── nbconvert!=5.4                                                 Converting Jupyter Notebooks
│   │   ├── bleach                                                     An easy safelist-based HTML-sanitizing tool.
│   │   │   ├── packaging                                              Core utilities for Python packages
│   │   │   │   └── pyparsing!=3.0.5,>=2.0.2                           Python parsing module
│   │   │   ├── six>=1.9.0                                             Python 2 and 3 compatibility utilities
│   │   │   └── webencodings                                           Character encoding aliases for legacy web content
│   │   ├── defusedxml                                                 XML bomb protection for Python stdlib modules
│   │   ├── entrypoints>=0.2.2                                         Discover and load entry points from installed packages.
│   │   ├── jinja2>=2.4                                                A very fast and expressive template engine.
│   │   │   └── MarkupSafe>=2.0                                        Safely add untrusted strings to HTML/XML markup.
│   │   ├── jupyter-core                                               Jupyter core package. A base package on which Jupyter projects rely.
│   │   │   └── traitlets                                              Traitlets Python configuration system
│   │   ├── jupyterlab-pygments                                        Pygments theme using JupyterLab CSS variables
│   │   │   └── pygments<3,>=2.4.1                                     Pygments is a syntax highlighting package written in Python.
│   │   ├── mistune<2,>=0.8.1                                          The fastest markdown parser in pure Python
│   │   ├── nbclient<0.6.0,>=0.5.0                                     A client library for executing notebooks. Formerly nbconvert's ExecutePreprocessor.
│   │   │   ├── jupyter-client>=6.1.5                                  Jupyter protocol implementation and client libraries
│   │   │   │   ├── entrypoints                                        Discover and load entry points from installed packages.
│   │   │   │   ├── jupyter-core>=4.6.0                                Jupyter core package. A base package on which Jupyter projects rely.
│   │   │   │   │   └── traitlets                                      Traitlets Python configuration system
│   │   │   │   ├── nest-asyncio>=1.5                                  Patch asyncio to allow nested event loops
│   │   │   │   ├── python-dateutil>=2.1                               Extensions to the standard Python datetime module
│   │   │   │   │   └── six>=1.5                                       Python 2 and 3 compatibility utilities
│   │   │   │   ├── pyzmq>=13                                          Python bindings for 0MQ
│   │   │   │   ├── tornado>=4.1                                       Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.
│   │   │   │   └── traitlets                                          Traitlets Python configuration system
│   │   │   ├── nbformat>=5.0                                          The Jupyter Notebook format
│   │   │   │   ├── ipython-genutils                                   Vestigial utilities from IPython
│   │   │   │   ├── jsonschema!=2.5.0,>=2.4                            An implementation of JSON Schema validation for Python
│   │   │   │   │   ├── attrs>=17.4.0                                  Classes Without Boilerplate
│   │   │   │   │   └── pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0  Persistent/Functional/Immutable data structures
│   │   │   │   ├── jupyter-core                                       Jupyter core package. A base package on which Jupyter projects rely.
│   │   │   │   │   └── traitlets                                      Traitlets Python configuration system
│   │   │   │   └── traitlets>=4.1                                     Traitlets Python configuration system
│   │   │   ├── nest-asyncio                                           Patch asyncio to allow nested event loops
│   │   │   └── traitlets>=4.2                                         Traitlets Python configuration system
│   │   ├── nbformat>=4.4                                              The Jupyter Notebook format
│   │   │   ├── ipython-genutils                                       Vestigial utilities from IPython
│   │   │   ├── jsonschema!=2.5.0,>=2.4                                An implementation of JSON Schema validation for Python
│   │   │   │   ├── attrs>=17.4.0                                      Classes Without Boilerplate
│   │   │   │   └── pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0      Persistent/Functional/Immutable data structures
│   │   │   ├── jupyter-core                                           Jupyter core package. A base package on which Jupyter projects rely.
│   │   │   │   └── traitlets                                          Traitlets Python configuration system
│   │   │   └── traitlets>=4.1                                         Traitlets Python configuration system
│   │   ├── pandocfilters>=1.4.1                                       Utilities for writing pandoc filters in python
│   │   ├── pygments>=2.4.1                                            Pygments is a syntax highlighting package written in Python.
│   │   ├── testpath                                                   Test utilities for code working with files and commands
│   │   └── traitlets>=5.0                                             Traitlets Python configuration system
│   ├── nbformat                                                       The Jupyter Notebook format
│   │   ├── ipython-genutils                                           Vestigial utilities from IPython
│   │   ├── jsonschema!=2.5.0,>=2.4                                    An implementation of JSON Schema validation for Python
│   │   │   ├── attrs>=17.4.0                                          Classes Without Boilerplate
│   │   │   └── pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0          Persistent/Functional/Immutable data structures
│   │   ├── jupyter-core                                               Jupyter core package. A base package on which Jupyter projects rely.
│   │   │   └── traitlets                                              Traitlets Python configuration system
│   │   └── traitlets>=4.1                                             Traitlets Python configuration system
│   ├── sphinx>=1.8                                                    Python documentation generator
│   │   ├── Jinja2>=2.3                                                A very fast and expressive template engine.
│   │   │   └── MarkupSafe>=2.0                                        Safely add untrusted strings to HTML/XML markup.
│   │   ├── Pygments>=2.0                                              Pygments is a syntax highlighting package written in Python.
│   │   ├── alabaster<0.8,>=0.7                                        A configurable sidebar-enabled Sphinx theme
│   │   ├── babel>=1.3                                                 Internationalization utilities
│   │   │   └── pytz>=2015.7                                           World timezone definitions, modern and historical
│   │   ├── docutils<0.18,>=0.14                                       Docutils -- Python Documentation Utilities
│   │   ├── imagesize                                                  Getting image size from png/jpeg/jpeg2000/gif file
│   │   ├── packaging                                                  Core utilities for Python packages
│   │   │   └── pyparsing!=3.0.5,>=2.0.2                               Python parsing module
│   │   ├── requests>=2.5.0                                            Python HTTP for Humans.
│   │   │   ├── certifi>=2017.4.17                                     Python package for providing Mozilla's CA Bundle.
│   │   │   ├── charset-normalizer~=2.0.0                              The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
│   │   │   ├── idna<4,>=2.5                                           Internationalized Domain Names in Applications (IDNA)
│   │   │   └── urllib3<1.27,>=1.21.1                                  HTTP library with thread-safe connection pooling, file post, and more.
│   │   ├── setuptools                                                 Easily download, build, install, upgrade, and uninstall Python packages
│   │   ├── snowballstemmer>=1.1                                       This package provides 29 stemmers for 28 languages generated from Snowball algorithms.
│   │   ├── sphinxcontrib-applehelp                                    sphinxcontrib-applehelp is a sphinx extension which outputs Apple help books
│   │   ├── sphinxcontrib-devhelp                                      sphinxcontrib-devhelp is a sphinx extension which outputs Devhelp document.
│   │   ├── sphinxcontrib-htmlhelp>=2.0.0                              sphinxcontrib-htmlhelp is a sphinx extension which renders HTML help files
│   │   ├── sphinxcontrib-jsmath                                       A sphinx extension which renders display math in HTML via JavaScript
│   │   ├── sphinxcontrib-qthelp                                       sphinxcontrib-qthelp is a sphinx extension which outputs QtHelp document.
│   │   └── sphinxcontrib-serializinghtml>=1.1.5                       sphinxcontrib-serializinghtml is a sphinx extension which outputs "serialized" HTML files (json and pickle).
│   └── traitlets                                                      Traitlets Python configuration system
├── numpy                                                              NumPy is the fundamental package for array computing with Python.
├── pandas                                                             Powerful data structures for data analysis, time series, and statistics
│   ├── numpy>=1.17.3                                                  NumPy is the fundamental package for array computing with Python.
│   ├── python-dateutil>=2.7.3                                         Extensions to the standard Python datetime module
│   │   └── six>=1.5                                                   Python 2 and 3 compatibility utilities
│   └── pytz>=2017.3                                                   World timezone definitions, modern and historical
├── pyparsing                                                          Python parsing module
├── python-dateutil                                                    Extensions to the standard Python datetime module
│   └── six>=1.5                                                       Python 2 and 3 compatibility utilities
├── pytz                                                               World timezone definitions, modern and historical
├── six                                                                Python 2 and 3 compatibility utilities
└── sphinx-rtd-theme                                                   Read the Docs theme for Sphinx
    ├── docutils<0.18                                                  Docutils -- Python Documentation Utilities
    └── sphinx>=1.6                                                    Python documentation generator
        ├── Jinja2>=2.3                                                A very fast and expressive template engine.
        │   └── MarkupSafe>=2.0                                        Safely add untrusted strings to HTML/XML markup.
        ├── Pygments>=2.0                                              Pygments is a syntax highlighting package written in Python.
        ├── alabaster<0.8,>=0.7                                        A configurable sidebar-enabled Sphinx theme
        ├── babel>=1.3                                                 Internationalization utilities
        │   └── pytz>=2015.7                                           World timezone definitions, modern and historical
        ├── docutils<0.18,>=0.14                                       Docutils -- Python Documentation Utilities
        ├── imagesize                                                  Getting image size from png/jpeg/jpeg2000/gif file
        ├── packaging                                                  Core utilities for Python packages
        │   └── pyparsing!=3.0.5,>=2.0.2                               Python parsing module
        ├── requests>=2.5.0                                            Python HTTP for Humans.
        │   ├── certifi>=2017.4.17                                     Python package for providing Mozilla's CA Bundle.
        │   ├── charset-normalizer~=2.0.0                              The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
        │   ├── idna<4,>=2.5                                           Internationalized Domain Names in Applications (IDNA)
        │   └── urllib3<1.27,>=1.21.1                                  HTTP library with thread-safe connection pooling, file post, and more.
        ├── setuptools                                                 Easily download, build, install, upgrade, and uninstall Python packages
        ├── snowballstemmer>=1.1                                       This package provides 29 stemmers for 28 languages generated from Snowball algorithms.
        ├── sphinxcontrib-applehelp                                    sphinxcontrib-applehelp is a sphinx extension which outputs Apple help books
        ├── sphinxcontrib-devhelp                                      sphinxcontrib-devhelp is a sphinx extension which outputs Devhelp document.
        ├── sphinxcontrib-htmlhelp>=2.0.0                              sphinxcontrib-htmlhelp is a sphinx extension which renders HTML help files
        ├── sphinxcontrib-jsmath                                       A sphinx extension which renders display math in HTML via JavaScript
        ├── sphinxcontrib-qthelp                                       sphinxcontrib-qthelp is a sphinx extension which outputs QtHelp document.
        └── sphinxcontrib-serializinghtml>=1.1.5                       sphinxcontrib-serializinghtml is a sphinx extension which outputs "serialized" HTML files (json and pickle).
```

### New (minimal):

```
johnnydep distinctipy==1.2.1
```

```
name                summary
------------------  -----------------------------------------------------------------
distinctipy==1.2.1  A lightweight package for generating visually distinct colours.
└── numpy           NumPy is the fundamental package for array computing with Python.
```

### New (optional):
```
johnnydep distinctipy[optional]==1.2.1
```
```
distinctipy[optional]==1.2.1          A lightweight package for generating visually distinct colours.
├── matplotlib                        Python plotting package
│   ├── cycler>=0.10                  Composable style cycles
│   ├── fonttools>=4.22.0             Tools to manipulate font files
│   ├── kiwisolver>=1.0.1             A fast implementation of the Cassowary constraint solver
│   ├── numpy>=1.17                   NumPy is the fundamental package for array computing with Python.
│   ├── packaging>=20.0               Core utilities for Python packages
│   │   └── pyparsing!=3.0.5,>=2.0.2  Python parsing module
│   ├── pillow>=6.2.0                 Python Imaging Library (Fork)
│   ├── pyparsing>=2.2.1              Python parsing module
│   └── python-dateutil>=2.7          Extensions to the standard Python datetime module
│       └── six>=1.5                  Python 2 and 3 compatibility utilities
├── numpy                             NumPy is the fundamental package for array computing with Python.
└── pandas                            Powerful data structures for data analysis, time series, and statistics
    ├── numpy>=1.17.3                 NumPy is the fundamental package for array computing with Python.
    ├── python-dateutil>=2.7.3        Extensions to the standard Python datetime module
    │   └── six>=1.5                  Python 2 and 3 compatibility utilities
    └── pytz>=2017.3                  World timezone definitions, modern and historical
```

**Pull request merged**
